print("Welcome to the tip calculator!")
total = float(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? 10 , 12, or 15?) "))
total_people = int(input("How many people to split the bill? "))
cost = round((total * (tip/100) + total) / total_people, 2)
print(f"Each person should pay: ${cost}")